/* Version definitions for the bundled libsigrokdecode 0.5.2. */
#ifndef LIBSIGROKDECODE_SRD_VERSION_H
#define LIBSIGROKDECODE_SRD_VERSION_H

#define SRD_PACKAGE_VERSION_MAJOR 0
#define SRD_PACKAGE_VERSION_MINOR 5
#define SRD_PACKAGE_VERSION_MICRO 2
#define SRD_PACKAGE_VERSION_STRING "0.5.2"

#define SRD_LIB_VERSION_CURRENT 6
#define SRD_LIB_VERSION_REVISION 0
#define SRD_LIB_VERSION_AGE 2
#define SRD_LIB_VERSION_STRING "6:0:2"

#endif
